"""에이전트Brain 모듈 - 블로그 글 구성 및 개선"""
import os
from typing import Optional, List
from openai import OpenAI
from utils.config import CONFIG
from agent.notebooklm import create_blog_post_from_response


class BlogBrain:
    """블로그 글을 구성하고 개선하는 AI 에이전트"""
    
    def __init__(self):
        """OpenAI 클라이언트 초기화"""
        self.client = OpenAI(api_key=CONFIG["openai_api_key"])
        self.model = "gpt-4o-mini"  # or "gpt-3.5-turbo"
    
    def plan_blog_structure(
        self,
        notebooklm_response: str,
        topic: Optional[str] = None
    ) -> dict:
        """
        NotebookLM 응답을 바탕으로 블로그 구조 계획
        
        Args:
            notebooklm_response: NotebookLM의 답변
            topic: 주제 (선택사항)
        
        Returns:
            블로그 구조 정보
        """
        prompt = f"""아래 NotebookLM의 답변을 바탕으로 블로그 포스트를 작성할 구조를 계획해주세요.

{notebooklm_response}

블로그 구조는 다음을 포함해야 합니다:
1.吸引人的 제목 (한글)
2.서론 (작은 소개)
3.주요 내용 (세부 사항)
4.요약

JSON 형식으로 응답해주세요:
{{
    "title": "블로그 제목",
    "introduction": "서론 내용",
    "sections": [
        {{"heading": "섹션 제목", "content": "섹션 내용"}},
        ...
    ],
    "conclusion": "결론 내용"
}}"""
        
        try:
            response = self.client.chat.completions.create(
                model=self.model,
                messages=[
                    {"role": "system", "content": "You are a helpful blog writer assistant."},
                    {"role": "user", "content": prompt}
                ],
                response_format={"type": "json_object"}
            )
            
            return {
                "structure": response.choices[0].message.content,
                "original_response": notebooklm_response
            }
        except Exception as e:
            return {"error": str(e), "fallback": notebooklm_response}
    
    def improve_response(
        self,
        original_response: str,
        improvement_request: str,
        topic: Optional[str] = None
    ) -> str:
        """
        NotebookLM 응답 개선
        
        Args:
            original_response: 원본 응답
            improvement_request: 개선 요청
            topic: 주제
        
        Returns:
            개선된 응답
        """
        prompt = f"""원본 답변을 참고해서 개선 요청사항을 반영해주세요.

원본 답변:
{original_response}

개선 요청사항:
{improvement_request}

주제: {topic or '알 수 없음'}

결과는 반드시 원본 답변의 내용을 유지하면서 개선 요청사항을 반영해주세요."""
        
        try:
            response = self.client.chat.completions.create(
                model=self.model,
                messages=[
                    {"role": "system", "content": "You are a helpful editor assistant."},
                    {"role": "user", "content": prompt}
                ]
            )
            return response.choices[0].message.content
        except Exception as e:
            return f"Error during improvement: {str(e)}"
    
    def generate_blog_from_notebook_response(
        self,
        question: str,
        notebook_response: str,
        auto_improve: bool = False,
        improve_prompt: Optional[str] = None
    ) -> dict:
        """
        NotebookLM 응답을 바탕으로 블로그 포스트 생성
        
        Args:
            question: 질문
            notebook_response: NotebookLM 응답
            auto_improve: 자동 개선 여부
            improve_prompt: 개선 프롬프트
        
        Returns:
            블로그 포스트 정보
        """
        # 기본 블로그 생성
        blog_post = create_blog_post_from_response(question, notebook_response)
        
        # 자동 개선
        if auto_improve and improve_prompt:
            improved = self.improve_response(
                notebook_response,
                improve_prompt,
                question
            )
            blog_post["content"] = improved
            blog_post["markdown"] = f"# {blog_post['title']}\n\n{improved}\n\n---\n*Generated by Blog Generator*"
            blog_post["improved"] = True
        
        return blog_post
    
    def multi_turn_question(
        self,
        question: str,
        context: Optional[str] = None,
        max_turns: int = 3
    ) -> List[dict]:
        """
        다중 회차 질문 - 복잡한 주제를 깊이 있게 탐색
        
        Args:
            question: 원래 질문
            context: 현재까지의 대화 컨텍스트
            max_turns: 최대 질문 회차
        
        Returns:
            질문-응답ペア 목록
        """
        conversation = []
        current_context = context or ""
        
        for turn in range(max_turns):
            prompt = f"""현재까지의 대화 컨텍스트:
{current_context}

다음 질문을 해주세요:
{question}

{'이전 답변을 바탕으로 더 깊이 있는 질문을 해주세요.' if turn > 0 else '이 질문에 대한 답변을 먼저 들어보세요.'}

질문을 만들어주세요 (답변이 길면后续 질문을 위해 key points를 물어보세요)."""
            
            try:
                response = self.client.chat.completions.create(
                    model=self.model,
                    messages=[
                        {"role": "system", "content": "You are a curious learner assistant."},
                        {"role": "user", "content": prompt}
                    ]
                )
                
                follow_up = response.choices[0].message.content
                conversation.append({"turn": turn + 1, "question": follow_up})
                
                current_context += f"\nQ: {follow_up}\nA: [待답]"
                
            except Exception as e:
                conversation.append({"error": str(e)})
                break
        
        return conversation
