"""NotebookLM 에이전트 모듈"""
import os
import asyncio
from typing import Optional, List
from notebooklm import NotebookLMClient, auth
from utils.config import CONFIG


class NotebookLMWrapper:
    """NotebookLM Wrapper 클래스"""
    
    def __init__(self):
        """
        NotebookLM 클라이언트 초기화
        """
        # Storage path 설정
        storage_path = CONFIG["data_dir"] / "notebooklm_storage"
        storage_path.mkdir(exist_ok=True)
        
        # 인증 토큰 로드
        auth_file = storage_path / "auth.json"
        if auth_file.exists():
            auth_tokens = auth.AuthTokens.from_storage(str(auth_file))
        else:
            # 최초 실행 - 수동 인증 필요
            print("NotebookLM 인증이 필요합니다.")
            print("브라우저에서 https://notebooklm.google.com/settings/api 에 접근해 API 토큰을 발급해주세요.")
            print("発급된 토큰을 사용하여 auth.json을 수동으로 생성해주세요.")
            raise NotImplementedError("NotebookLM 인증이 필요합니다.")
        
        self.client = NotebookLMClient(auth=auth_tokens)
        self.notebook_id = CONFIG["notebooklm_notebook_id"]
    
    async def ask_question(
        self,
        question: str,
        notebook_id: Optional[str] = None,
        context: Optional[str] = None
    ) -> str:
        """
        NotebookLM에 질문하기
        
        Args:
            question: 질문 내용
            notebook_id: 사용할 노트북 ID (생략 시 기본 노트북)
            context: 추가적인 문맥 정보
        
        Returns:
            NotebookLM의 답변
        """
        target_notebook_id = notebook_id or self.notebook_id
        
        # 질문 생성
        if context:
            prompt = f"문맥 정보:\n{context}\n\n질문:\n{question}"
        else:
            prompt = question
        
        try:
            async with self.client as client:
                # NotebookLM의 ask API 사용
                response = await client.ask(prompt, notebook_id=target_notebook_id)
                return response.text if hasattr(response, "text") else str(response)
                
        except Exception as e:
            return f"Error: {str(e)}"
    
    async def get_notebook_info(self, notebook_id: Optional[str] = None) -> dict:
        """
        노트북 정보 조회
        
        Args:
            notebook_id: 조회할 노트북 ID
        
        Returns:
            노트북 정보
        """
        target_id = notebook_id or self.notebook_id
        try:
            async with self.client as client:
                metadata = await client.get_metadata(target_id)
                
                return {
                    "id": metadata.id if hasattr(metadata, "id") else target_id,
                    "name": metadata.title if hasattr(metadata, "title") else "Unknown",
                    "document_count": len(metadata.source_summaries) if hasattr(metadata, "source_summaries") else 0
                }
        except Exception as e:
            return {"error": str(e)}
    
    async def list_notebooks(self) -> List[dict]:
        """사용 가능한 노트북 목록 조회"""
        try:
            async with self.client as client:
                notebooks = await client.list_notebooks()
                
                return [
                    {
                        "id": nb.id if hasattr(nb, "id") else "Unknown",
                        "name": nb.title if hasattr(nb, "title") else "Unknown"
                    }
                    for nb in notebooks
                ]
        except Exception as e:
            return [{"error": str(e)}]


def create_blog_post_from_response(
    question: str,
    response: str,
    title_prefix: str = ""
) -> dict:
    """
    NotebookLM 응답을 바탕으로 블로그 포스트 생성
    
    Args:
        question: 질문
        response: 답변
        title_prefix: 제목 접두사
    
    Returns:
        블로그 포스트 정보 (title, content, markdown)
    """
    # 제목 생성 (간단한 방식)
    if title_prefix:
        title = f"{title_prefix}: {question[:30]}"
    else:
        title = question[:50]
    
    # 마크다운 내용
    markdown = f"# {title}\n\n{response}\n\n---\n*Generated by Blog Generator*"
    
    return {
        "title": title,
        "content": response,
        "markdown": markdown
    }
